import java.sql.*;
import javax.swing.JOptionPane;
/* To change this template, choose Tools | Templates
* and open the template in the editor.
*/

/*
 * deletemodify.java
 *
 *
 */

/**
 *
 * @author sakshi
 */
public class deletemodify extends javax.swing.JFrame {
    Connection con;
    String s6, s, s1, s3, s4, s0 = "1233";
    int pin;
    /** Creates new form deletemodify */
    public deletemodify() {
        try {
            Class.forName("java.sql.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/student", "root", "");
        } catch (Exception e1) {System.out.println("ERROR=" + e1);}

        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tf = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        l = new javax.swing.JLabel();
        b3 = new javax.swing.JButton();
        tfadd = new javax.swing.JTextField();
        tfPhone = new javax.swing.JTextField();
        tfemail = new javax.swing.JTextField();
        tfdob = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        l3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 307));
        getContentPane().setLayout(null);

        jButton1.setForeground(new java.awt.Color(51, 51, 0));
        jButton1.setText("delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(60, 250, 100, 23);

        jButton2.setForeground(new java.awt.Color(51, 51, 0));
        jButton2.setText("modify");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(170, 250, 120, 23);
        getContentPane().add(tf);
        tf.setBounds(290, 100, 130, 20);

        b1.setText("Search");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(310, 60, 110, 23);

        l.setFont(new java.awt.Font("Broadway", 0, 11));
        l.setForeground(new java.awt.Color(51, 51, 0));
        l.setText("Search By Name");
        getContentPane().add(l);
        l.setBounds(70, 100, 99, 13);

        b3.setForeground(new java.awt.Color(51, 51, 0));
        b3.setText("Exit");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3);
        b3.setBounds(410, 290, 90, 23);
        getContentPane().add(tfadd);
        tfadd.setBounds(290, 130, 160, 20);
        getContentPane().add(tfPhone);
        tfPhone.setBounds(290, 160, 130, 20);
        getContentPane().add(tfemail);
        tfemail.setBounds(290, 190, 130, 20);
        getContentPane().add(tfdob);
        tfdob.setBounds(290, 220, 130, 20);

        jLabel1.setFont(new java.awt.Font("Broadway", 0, 11));
        jLabel1.setForeground(new java.awt.Color(51, 51, 0));
        jLabel1.setText("Address");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 130, 70, 13);

        jLabel2.setFont(new java.awt.Font("Broadway", 0, 11));
        jLabel2.setForeground(new java.awt.Color(51, 51, 0));
        jLabel2.setText("e-mail");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 160, 50, 13);

        jLabel3.setFont(new java.awt.Font("Broadway", 0, 11));
        jLabel3.setForeground(new java.awt.Color(51, 51, 0));
        jLabel3.setText("Date-Of -Birth");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 220, 90, 10);

        jLabel4.setFont(new java.awt.Font("Broadway", 0, 11));
        jLabel4.setForeground(new java.awt.Color(51, 51, 0));
        jLabel4.setText("Phone no.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 190, 80, 13);

        jButton3.setForeground(new java.awt.Color(51, 51, 0));
        jButton3.setText("clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(300, 250, 90, 23);

        jButton4.setText("Home");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(10, 10, 160, 23);

        l3.setBackground(new java.awt.Color(153, 153, 0));
        l3.setFont(new java.awt.Font("Monotype Corsiva", 3, 36));
        l3.setForeground(new java.awt.Color(51, 51, 0));
        l3.setText("ADDRESS    BOOK");
        getContentPane().add(l3);
        l3.setBounds(70, 20, 310, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diary_large.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 500, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        try {

            Date d;
            //Long s2;
            int s5, s2;
            s = tf.getText().trim();


            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("Select * From address");
            while (rs.next()) {

                s1 = rs.getString(2);
                s2 = rs.getInt(3);
                s3 = rs.getString(4);
                s4 = rs.getString(5);
                d =  rs.getDate(6);
                System.out.println("got string");
                if ((s1.trim().equals(s))) {
                    tfPhone.setText(s2 + "");
                    tfadd.setText(s3);
                    tfemail.setText(s4);
                    tfdob.setText(d + "");
                    pin = rs.getInt(1);
                }//eoif
            }//eowhlie
        } catch (Exception e1) {System.out.println("ERROR=" + e1);}
    }//GEN-LAST:event_b1ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        try {
            System.exit(0);
        } catch (Exception e3) {}
    }//GEN-LAST:event_b3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String s11, s12, s13;
            PreparedStatement ps = con.prepareStatement("delete from address where aid=" + pin);
            //ps.setString(0,"");
            //ps.setString(4,pin+"");

            int i = ps.executeUpdate();
            System.out.println("Row Updated:" + i);
            JOptionPane.showMessageDialog(this, "Record deleted successfully..");
            jButton3ActionPerformed(evt);
        } catch (Exception e1) {System.out.println("ERROR=" + e1);}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            String name = tf.getText();
            int phone = Integer.parseInt(tfPhone.getText());
            String add = tfadd.getText();
            String email = tfemail.getText();
            Date d = Date.valueOf(tfdob.getText());
            PreparedStatement ps = con.prepareStatement("update address set aname=?, phone=?, address=?, email=?, dob=? where aid=" + pin);
            ps.setString(1, "0");
            ps.setString(1, name);
            ps.setInt(2, phone);
            ps.setString(3, add);
            ps.setString(4, email);
            ps.setDate(5, d);
            int i = ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record modified successfully..");
            jButton4ActionPerformed(evt);
        } catch (Exception e1) {System.out.println(e1);}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        tf.setText(" ");
        tfadd.setText(" ");
        tfPhone.setText(" ");
        tfemail.setText(" ");
        tfdob.setText(" ");
        pin = 0;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.hide();
        start st = new start();
        st.show();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deletemodify().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel l;
    private javax.swing.JLabel l3;
    private javax.swing.JTextField tf;
    private javax.swing.JTextField tfPhone;
    private javax.swing.JTextField tfadd;
    private javax.swing.JTextField tfdob;
    private javax.swing.JTextField tfemail;
    // End of variables declaration//GEN-END:variables

}
